### ISSUE TITLE
Question: Secure value showing as plaintext in output

### ISSUE THREAD

**Issue by shbedev** [terraform-aws-modules/terraform-aws-ssm-parameter#2]
I am trying to understand the purpose of showing the SecureString value as plaintext in the `value` output.
Isn't it defeat the whole purpose of the `sensitive` option?

**Comment by antonbabenko** [comment]
There are multiple outputs - value, secure_value, insecure_value. One of these should be sufficient for the user's needs.

It is rather hard and limiting to work with `sensitive` values in the module and there is no easy way to make `value` sensitive conditionally (e.g. based on the type).

Hopefully, I answer your question.
