### ISSUE TITLE
Ignore changes to the Version when ignore_value_changes is set to True

### ISSUE THREAD

**Issue by blueelvis** [terraform-aws-modules/terraform-aws-ssm-parameter#4]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

## Versions

- Module version [Required]: `1.1.0`

- Terraform version: Terraform v1.6.3
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.36.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

## Reproduction Code [Required]
```
module "docker_image_ssm" {
  source  = "terraform-aws-modules/ssm-parameter/aws"
  version = "1.1.0"

  ignore_value_changes = true

  name  = "/docker_image"
  value = "REPLACE_ME"
}
```

1. Apply the above Terraform.
2. Modify the value of the SSM parameter manually.
3. Do a Terraform plan again and you will notice the following -
```
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:
  # module.docker_image_ssm.aws_ssm_parameter.ignore_value[0] has changed
  ~ resource "aws_ssm_parameter" "ignore_value" {
        id             = "/docker_image"
      ~ insecure_value = "REPLACE_ME" -> "***.dkr.ecr.us-east-2.amazonaws.com/hello-02ca40c02"
        name           = "/docker_image"
        tags           = {}
      ~ version        = 1 -> 9
        # (5 unchanged attributes hidden)
    }
Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
```
**Are you using workspaces?**
Yes, we are using workspaces.

## Expected behavior
1. No changes are detected from outside when the value is changed.

## Actual behavior

Terraform is complaining that changes have been performed outside of Terraform.

**Comment by antonbabenko** [comment]
This is expected behaviour in the module because value has been changed outside of Terraform (`Note: Objects have changed outside of Terraform). It is also important to see that the `terraform plan` is not planning to revert those changes back to the original value (`"REPLACE_ME"`).

More details here - https://github.com/hashicorp/terraform/issues/28803
